on: [push]


jobs:
  call-classroom-workflow:
    uses: GittyBitch/tabot-workflows/.github/workflows/classroom.yml@main
    with:
      log-level: 'debug'
#secrets:
#GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Replace with actual secrets
